### ISSUE TITLE
MatLab call for statistics

### ISSUE THREAD

**Issue by alexwalterbos** [alexwalterbos/image-reconstruction#14]
http://www.mathworks.nl/help/matlab/matlab_external/call-matlab-function-from-a-c-client.html

**Comment by festen** [comment]
Ik heb iets soortgelijks gebruikt in Parijs voor de ANAC competitie. Daar kon je vanuit Java in real-time variablen en functies naar matlab exporteren. Dit was alleen echt veel werk. Ik denk dat je gewoon een CSV bestandje moet exporteren en importeren, veel sneller.

**Comment by alexwalterbos** [comment]
Ik sla inderdaad de data gewoon op in een bestand, maar ik neem aan dat de link met MatLab hier op in de link beschreven manier wel nuttig is?

**Comment by alexwalterbos** [comment]
http://www.codeproject.com/Articles/594636/Using-Matlab-from-a-Csharp-application
