### ISSUE TITLE
Saving images crashes program

### ISSUE THREAD

**Issue by festen** [alexwalterbos/image-reconstruction#8]
@ASchutter mentioned that for him, running the program crashes on saving images.
Can you give us the necessary steps to reproduce this error? As I myself do not have this error. (Which branch to start with?)

@AlexWalterbos Do you also have this issue?

**Comment by alexwalterbos** [comment]
I don't have that issue!

**Comment by festen** [comment]
I think it is because @ASchutter used an outdated version. Master is working anyway. Closing issue
